# workflow name
name: linux-gcc

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: chmod +x premake5 && ./premake5 gmake
      - name: build
        run: make -j2 config=release
      - name: test
        run: chmod +x moon && ./moon -c example/config.json -r 1
