# workflow name
name: CI

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: chmod +x premake5 && ./premake5 gmake config=release
      - name: build
        run: make -j2 config=release
      - name: test
        run: chmod +x moon && ./moon -c example/config.json -r 1

  linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: chmod +x premake5 && ./premake5 gmake --cc=clang
      - name: build
        run: make -j2 config=release
      - name: test
        run: chmod +x moon && ./moon -c example/config.json -r 1

  macos-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: chmod +x premake5-macosx && ./premake5-macosx gmake --cc=clang
      - name: build
        run: make -j2 config=release
      - name: test
        run: chmod +x moon && ./moon -c example/config.json -r 1

  windows-vs2019:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: .\premake5.exe vs2019
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: build
        run: msbuild /m Server.sln /p:configuration="release"
      - name: test
        run: .\moon.exe -c example/config.json -r 1