
# Workflow's name
name: Release moon

# Workflow's trigger
on:
  push:
    tags:
      - 'v*.*'

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release moon
    
    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}
    
    # create a build matrix for jobs
    strategy:
      matrix:
        os: [windows-latest]

    # create steps
    steps:
      - uses: actions/checkout@v2
      - name: Setup premake
        uses: abel0b/setup-premake@v1
      - name: configure
        run: premake5.exe vs2019
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: build
        run: msbuild /m Server.sln /p:configuration="release"
      - uses: actions/upload-artifact@v2
        with:
          name: windows-2019-MSVC16-release
          path: |
            lualib/
            service/
            moon.exe